import type { CSSProperties } from "react";

/** Co-located styles for the shared ProjectContextPicker. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    marginBottom: 8,
  } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 260,
    marginBottom: 8,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  orderHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginBottom: 12,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  row: (attached: boolean) =>
    ({
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "9px 12px",
      borderRadius: 8,
      border: "1px solid var(--border)",
      background: attached ? "var(--bg-hover)" : "var(--bg-surface)",
      opacity: attached ? 1 : 0.75,
      marginBottom: 6,
    }) satisfies CSSProperties,
  dragHandle: {
    color: "var(--text-muted)",
    cursor: "grab",
    display: "inline-flex",
    flexShrink: 0,
  } satisfies CSSProperties,
  orderNum: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    minWidth: 14,
    textAlign: "right",
  } satisfies CSSProperties,
  path: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rootTag: (color: string) =>
    ({
      fontSize: 10.5,
      fontWeight: 600,
      padding: "1px 8px",
      borderRadius: 4,
      color,
      background: `${color}1a`,
      whiteSpace: "nowrap",
    }) satisfies CSSProperties,
  tokens: { fontSize: 11.5, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  miniBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 3,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  moveBtns: { display: "inline-flex", gap: 4 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    marginTop: 10,
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerTokens: { fontSize: 13, fontWeight: 650, whiteSpace: "nowrap" } satisfies CSSProperties,
  footerNote: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.45 } satisfies CSSProperties,
  skillNote: {
    marginTop: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  skillNoteText: { margin: "0 0 8px", fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.45 } satisfies CSSProperties,
  serializesTitle: { margin: "0 0 4px", fontSize: 11, fontWeight: 700, letterSpacing: 0.4, color: "var(--text-muted)" } satisfies CSSProperties,
  serializesBox: {
    margin: 0,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
    fontSize: 12,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "12px 0", lineHeight: 1.5 } satisfies CSSProperties,
  /** The vendored Modal's body wrapper is unpadded (INSIGHT 2026-09-22). */
  previewBody: { padding: 24, maxHeight: "70vh", overflow: "auto" } satisfies CSSProperties,
} as const;
