import type { CSSProperties } from "react";

/** Styles for the Onboarding Tour page: header, two-column layout, cards, TOC rail. */
export const s = {
  page: { padding: "28px 32px", maxWidth: 1160, margin: "0 auto" } satisfies CSSProperties,
  heading: { fontSize: 26, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 18,
    lineHeight: 1.5,
    maxWidth: 720,
  } satisfies CSSProperties,
  factsRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 16,
  } satisfies CSSProperties,
  factsLine: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  modelChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    padding: "3px 10px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  actionsRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 14,
    marginBottom: 8,
  } satisfies CSSProperties,
  shareStatus: { fontSize: 12, color: "var(--ok)" } satisfies CSSProperties,
  shareFallback: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: 0,
  } satisfies CSSProperties,
  shareFallbackUrl: {
    fontSize: 12.5,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "4px 8px",
    userSelect: "all",
  } satisfies CSSProperties,

  columns: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 224px",
    gap: 28,
    alignItems: "start",
  } satisfies CSSProperties,
  main: { display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,
  rail: { position: "sticky", top: 16 } satisfies CSSProperties,
  skeletonList: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,

  // ---- section card ----
  card: {
    borderRadius: 10,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    padding: "16px 18px",
    scrollMarginTop: 24,
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  cardTitle: { fontSize: 16, fontWeight: 650, flex: 1, margin: 0 } satisfies CSSProperties,
  collapseBtn: {
    display: "grid",
    placeItems: "center",
    width: 26,
    height: 26,
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    padding: 0,
  } satisfies CSSProperties,
  cardBody: { marginTop: 12 } satisfies CSSProperties,
  emptyNote: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
    lineHeight: 1.5,
  } satisfies CSSProperties,

  // ---- architecture ----
  diagram: { marginTop: 12 } satisfies CSSProperties,

  // ---- path rows (critical paths / reading path) ----
  rowList: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowIndex: { fontSize: 12, color: "var(--text-muted)", minWidth: 16 } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowPath: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-text)",
    textDecoration: "none",
  } satisfies CSSProperties,
  rowPathPlain: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  rowText: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    margin: "3px 0 0",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  openLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "var(--accent)",
    textDecoration: "none",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  prRef: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    borderRadius: 5,
    padding: "1px 6px",
  } satisfies CSSProperties,

  // ---- run-locally steps ----
  stepRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  stepMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  stepTitleRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  } satisfies CSSProperties,
  stepTitle: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  stepDesc: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    margin: "2px 0 8px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  commandRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  command: {
    flex: 1,
    minWidth: 0,
    margin: 0,
    padding: "7px 10px",
    fontSize: 12.5,
    lineHeight: 1.5,
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  copyStatus: { fontSize: 12, color: "var(--ok)", whiteSpace: "nowrap" } satisfies CSSProperties,
  stepDone: { fontSize: 13, color: "var(--text-secondary)", marginTop: 2 } satisfies CSSProperties,
  stepDoneChecked: { color: "var(--text-primary)" } satisfies CSSProperties,

  // ---- TOC rail ----
  toc: {
    borderRadius: 10,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    padding: "12px 14px",
  } satisfies CSSProperties,
  tocLabel: { marginBottom: 10 } satisfies CSSProperties,
  tocProgress: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 999,
    padding: "3px 10px",
    marginBottom: 12,
  } satisfies CSSProperties,
  tocList: { display: "flex", flexDirection: "column", gap: 2, listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  tocItem: {
    textAlign: "left",
    fontSize: 12.5,
    padding: "6px 8px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    width: "100%",
  } satisfies CSSProperties,
  tocItemActive: {
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    fontWeight: 600,
  } satisfies CSSProperties,
  tocItemRead: { color: "var(--text-primary)" } satisfies CSSProperties,
} as const;
