import type { CSSProperties } from "react";

/** Co-located styles for the (read-only) Project Context page view. */
export const s = {
  page: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  heading: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  repoName: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-muted)",
    marginLeft: 10,
  } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5, margin: 0 } satisfies CSSProperties,
  columns: { display: "grid", gridTemplateColumns: "320px 1fr", gap: 16, alignItems: "start" } satisfies CSSProperties,
  tree: {
    padding: "12px 10px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    maxHeight: "70vh",
    overflow: "auto",
  } satisfies CSSProperties,
  treeTitle: {
    margin: "0 0 8px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.4,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  group: { marginBottom: 10 } satisfies CSSProperties,
  groupHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 650,
    color: "var(--text-secondary)",
    padding: "4px 6px",
  } satisfies CSSProperties,
  docRow: (active: boolean) =>
    ({
      display: "flex",
      alignItems: "center",
      gap: 8,
      width: "100%",
      textAlign: "left",
      padding: "6px 8px 6px 24px",
      borderRadius: 6,
      border: "1px solid transparent",
      background: active ? "var(--bg-hover)" : "transparent",
      color: active ? "var(--text-primary)" : "var(--text-secondary)",
      cursor: "pointer",
      fontSize: 13,
    }) satisfies CSSProperties,
  docPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.5,
  } satisfies CSSProperties,
  rowTokens: { fontSize: 11, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  reader: {
    padding: "14px 18px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minHeight: 320,
  } satisfies CSSProperties,
  readerHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  readerPath: { fontSize: 12.5, fontWeight: 600, flex: 1, minWidth: 0 } satisfies CSSProperties,
  readerTokens: { fontSize: 11.5, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  footer: { fontSize: 12, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
} as const;
