import type { CSSProperties } from "react";

/* One border declaration per element — `border` shorthand for full borders,
   `borderTop` alone for rules (never shorthand + longhand mixed: React 19
   dev-mode warns on conflicting border properties during rerender). */
export const s = {
  liveRegion: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginBottom: 10,
  } satisfies CSSProperties,
  staleNote: {
    fontSize: 12.5,
    color: "var(--warn)",
  } satisfies CSSProperties,
  missingNote: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  generatingNote: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  errorNote: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 12.5,
    color: "var(--crit)",
  } satisfies CSSProperties,
  verdictWrap: {
    marginBottom: 14,
  } satisfies CSSProperties,
  blockLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "4px 0 6px",
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  riskList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  riskRow: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg)",
    padding: "7px 10px",
  } satisfies CSSProperties,
  riskHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
    font: "inherit",
  } satisfies CSSProperties,
  sevLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskRefs: {
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskChevron: {
    color: "var(--text-muted)",
    flexShrink: 0,
    marginLeft: "auto",
    transition: "transform .12s",
  } satisfies CSSProperties,
  riskBody: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
  } satisfies CSSProperties,
  emptyList: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  focusButton: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
    font: "inherit",
    fontSize: 13,
  } satisfies CSSProperties,
  focusStep: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 18,
    height: 18,
    padding: "0 5px",
    borderRadius: 999,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
    alignSelf: "center",
  } satisfies CSSProperties,
  focusPath: {
    fontSize: 12.5,
    color: "var(--accent)",
  } satisfies CSSProperties,
  notInDiff: {
    fontSize: 11,
    fontStyle: "italic",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusReason: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 14,
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
