import type { CSSProperties } from "react";

/* One border declaration per element — `border` shorthand for full borders,
   `borderTop` alone for rules (never shorthand + longhand mixed: React 19
   dev-mode warns on conflicting border properties during rerender). */
export const s = {
  subtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginBottom: 12,
  } satisfies CSSProperties,
  statRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 18,
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg)",
    marginBottom: 12,
  } satisfies CSSProperties,
  statItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  statCount: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  degradedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 4,
  } satisfies CSSProperties,
  resyncNote: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 12,
  } satisfies CSSProperties,
  viewToggle: {
    display: "inline-flex",
    gap: 4,
  } satisfies CSSProperties,
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  group: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg)",
    padding: "8px 12px",
  } satisfies CSSProperties,
  groupHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
    font: "inherit",
  } satisfies CSSProperties,
  symbolIcon: {
    color: "var(--accent)",
    flexShrink: 0,
  } satisfies CSSProperties,
  symbolName: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolMeta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  callerCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  groupBody: {
    marginTop: 6,
  } satisfies CSSProperties,
  callerList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    paddingLeft: 2,
  } satisfies CSSProperties,
  callerGlyph: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  callerLink: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    color: "var(--accent)",
  } satisfies CSSProperties,
  callerName: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  } satisfies CSSProperties,
  endpointBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "2px 9px",
    border: "1px solid var(--accent)",
    borderRadius: 999,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  endpointMethod: {
    fontWeight: 700,
  } satisfies CSSProperties,
  cronBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "2px 9px",
    border: "1px solid var(--warn)",
    borderRadius: 999,
    background: "var(--warn-bg)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  badgeMore: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 11.5,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--accent)",
    cursor: "pointer",
  } satisfies CSSProperties,
  divider: {
    borderTop: "1px solid var(--border)",
    marginTop: 14,
  } satisfies CSSProperties,
  historyRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    font: "inherit",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  historyCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 18,
    height: 18,
    padding: "0 6px",
    borderRadius: 999,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  historyChevron: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  historyList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: 10,
  } satisfies CSSProperties,
  historyItem: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg)",
    padding: "10px 12px",
  } satisfies CSSProperties,
  historyItemTitle: {
    fontSize: 13.5,
    color: "var(--text-primary)",
    fontWeight: 600,
  } satisfies CSSProperties,
  historyItemNumber: {
    fontVariantNumeric: "tabular-nums",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  historyItemLink: {
    color: "var(--accent)",
  } satisfies CSSProperties,
  historyItemTitleText: {
    fontWeight: 600,
  } satisfies CSSProperties,
  historyItemMeta: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 2,
  } satisfies CSSProperties,
  historyNotes: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 6,
  } satisfies CSSProperties,
  graphLegend: {
    display: "flex",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 8,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  legendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 4,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    flexShrink: 0,
  } satisfies CSSProperties,
  graphTrimmed: {
    marginTop: 6,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  noCallers: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: 4,
  } satisfies CSSProperties,
  noDownstream: {
    fontSize: 13.5,
    color: "var(--text-secondary)",
    padding: "14px 0 4px",
  } satisfies CSSProperties,
  errorText: {
    fontSize: 13.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
